// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	setActivity: (activity: Activity) => typedError<null, string>(__TAURI_INVOKE("set_activity", { activity })),
	clearActivity: () => typedError<null, string>(__TAURI_INVOKE("clear_activity")),
};

/* Types */
export type Activity = {
	state?: string | null,
	details?: string | null,
	instance?: boolean | null,
	statusDisplayType?: StatusDisplayType | null,
	activityType?: ActivityType | null,
	timestamps?: ActivityTimestamps | null,
	assets?: ActivityAssets | null,
	party?: ActivityParty | null,
	secrets?: ActivitySecrets | null,
	buttons?: ActivityButton[],
};

export type ActivityAssets = {
	largeImage?: string | null,
	largeText?: string | null,
	smallImage?: string | null,
	smallText?: string | null,
};

export type ActivityButton = {
	label?: string | null,
	url?: string | null,
};

export type ActivityParty = {
	id?: string | null,
	size?: [number, number] | null,
};

export type ActivitySecrets = {
	join?: string | null,
	spectate?: string | null,
	match?: string | null,
};

export type ActivityTimestamps = {
	start?: number | null,
	end?: number | null,
};

export type ActivityType = "playing" | "listening" | "watching" | "competing";

export type StatusDisplayType = "name" | "state" | "details";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

